pipeline {
    agent any
    stages {
        stage('Build') { 
            steps {
                dir("RestAPISpringBoot") {
                    sh 'chmod a+x mvnw'
                    sh "./mvnw package" 
                }
            }
        }
        
        stage('Dockerize') { 
            steps {
                dir("RestAPISpringBoot") {
                    sh 'docker build -t ${DOCKER_IMAGE}' 
                }
            }
        }
        
        stage('Publish into DockerHUB') {
            when {
                branch 'master'
            }
            steps {
                withDockerRegistry([ credentialsId: "${DOCKER_HUB_ID}", url: "" ]) {
                    sh 'docker push ${DOCKER_IMAGE}:latest'
                }            
            }
        }
    }
}
